export const FETCH_ARTICLES = 'FETCH_ARTICLES';

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';

export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';



export const FETCH_ARTICLE = 'FETCH_ARTICLE';

export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';

export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';



export const CREATE_ARTICLE = 'CREATE_ARTICLE';

export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';

export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';



export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';

export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';

export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE';



export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';

export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';



export const RESET_NEW_ARTICLE = 'RESET_NEW_ARTICLE';

export const RESET_ACTIVE_ARTICLE = 'RESET_ACTIVE_ARTICLE';

export const RESET_ARTICLES = 'RESET_ARTICLES';

export const RESET_DELETED_ARTICLE = 'REST_DELETED_ARTICLE';

export const RESET_UPDATED_ARTICLE = 'RESET_UPDATED_ARTICLE';