export const VALIDATE_USER_FIELDS = 'VALIDATE_USER_FIELDS';

export const VALIDATE_USER_FIELDS_SUCCESS = 'VALIDATE_USER_FIELDS_SUCCESS';

export const VALIDATE_USER_FIELDS_FAILURE = 'VALIDATE_USER_FIELDS_FAILURE';

export const RESET_VALIDATE_USER_FIELDS = 'RESET_VALIDATE_USER_FIELDS';